// Autogenerated using npm run gen App
/*
* Copy to other files
* import App from './App';
* <App/>
*/
import styled from 'styled-components';
import { Switch, Route } from 'react-router-dom';
import ERROR404 from './ERROR404';
import Header from './Header';

function App(){
  return (
    <Main>
      <Header/>
      <h1>App Component Created Successfully</h1>
      <Switch>
        <Route exact path='/'/>
        <Route component={ERROR404} />
      </Switch>
    </Main>
  );
}

/*
App.propTypes = {
  //  [variable-name]: PropTypes.[type],
};
*/

export default App;

const Main = styled.div`
background-color: black;
font-family: sans-serif;
padding-top: 50px;
color: white;
`;
