// Autogenerated using npm run gen Chat
/*
* Copy to other files
* import Chat from './Chat';
* <Chat/>
*/
import styled from 'styled-components';
import Message from './Message';
import MessageForm from './MessageForm';

//Contains current dicusion for selected group

function Chat(props){

  return (
    <Main>
      {props.messageList.map((message,i) =>
        <Message message={message.message}
          key={i}/>
      )}
      <MessageForm/>
    </Main>
  );


}

Chat.propTypes = {
  messageList: PropTypes.array,
};

export default Chat;

const Main = styled.div`

`;
