// Autogenerated using npm run gen Chat
/*
* Copy to other files
* import Chat from './Chat';
* <Chat/>
*/
import styled from 'styled-components';
import Message from './Message';
// import PropTypes from 'prop-types';
// import { Link, Switch, Route } from 'react-router-dom';

//Contains current dicusion for selected group

function Chat(props){

  return (
    <Main>
      {props.messageList.map((message,i) =>
        <Message message={message}
          key={i}/>
      )}
      <div className='row'>
        <div classname='col-md-9'>
          <textarea placeholder='Message Box' cols='100'></textarea>
        </div>
        <div classname='col-md-3'>
          <button className='btn btn-submit'>Submit</button>
        </div>
      </div>
    </Main>
  );


}


Chat.propTypes = {
  messageList: PropTypes.array,
};


export default Chat;

const Main = styled.div`

`;
