// Autogenerated using npm run gen ChatList
/*
* Copy to other files
* import ChatList from './ChatList';
* <ChatList/>
*/
import styled from 'styled-components';
import Chat from './Chat';

//List chats by chat names pass name and uuid

function ChatList(){
  return (
    <Main>
      <h1>Current Discussions</h1>
      <h2>Chat List One</h2>
      <Chat messageList={chatOne}/>
      <h2>Chat List Two</h2>
      <Chat messageList={chatTwo}/>
    </Main>
  );
}

export default ChatList;

const Main = styled.div`
background-color: black;
font-family: sans-serif;
color: white;
`;

const chatOne = [{message:'Hi'},{message:'Yay'},{message:'Test One'}];
const chatTwo = [{message:'Hi'},{message:'Yay'},{message:'Test Two'}];
