// Autogenerated using npm run gen Contact
/*
* Copy to other files
* import Contact from './Contact';
* <Contact/>
*/
import styled from 'styled-components';
// import { Link, Switch, Route } from 'react-router-dom';

function Contact(props){
  return (
    <Main>
      <Name>{props.firstname} {props.lastName}</Name>
    </Main>
  );
}

/*
Contact.propTypes = {
  //  [variable-name]: PropTypes.[type],
};
*/

export default Contact;

const Main = styled.div`
background-color: black;
font-family: sans-serif;
color: white;
`;

const Name = styled.h4`
background-color: black;
&:hover ${Name} {
  background-color: blue;
}
`;
