// Autogenerated using npm run gen Contacts
/*
* Copy to other files
* import Contacts from './Contacts';
* <Contacts/>
*/
import styled from 'styled-components';
// import PropTypes from 'prop-types';
// import { Link, Switch, Route } from 'react-router-dom';

function Contacts(){
  return (
    <Main>
      <h1>Contacts Component Created Successfully</h1>
    </Main>
  );
}

/*
Contacts.propTypes = {
  //  [variable-name]: PropTypes.[type],
};
*/

export default Contacts;

const Main = styled.div`
background-color: black;
font-family: sans-serif;
color: white;
`;
