// Autogenerated using npm run gen ERROR404
/*
* Copy to other files
* import ERROR404 from './ERROR404';
* <ERROR404/>
*/
import styled from 'styled-components';
// import { Link, Switch, Route } from 'react-router-dom';

function ERROR404(){
  return (
    <Main>
      <h1>ERROR404 Component Created Successfully</h1>
    </Main>
  );
}

/*
ERROR404.propTypes = {
  //  [variable-name]: PropTypes.[type],
};
*/

export default ERROR404;

const Main = styled.div`

`;
