// Autogenerated using npm run gen Error404
/*
* Copy to other files
* import Error404 from './Error404';
* <Error404/>
*/
import { Link } from 'react-router-dom';
import styled from 'styled-components';

function Error404(props){
  return (
    <Main>
      <h2>The page {props.location.pathname} does not exist!</h2>
      <h3>Would you like to return <Link to="/">home</Link> instead?</h3>
    </Main>
  );
}

Error404.propTypes = {
  location: PropTypes.string,
};

export default Error404;

const Main = styled.div`
color: white;
text-align: center;
font-size: 1em;
`;
