// Autogenerated using npm run gen Groups
/*
* Copy to other files
* import Groups from './Groups';
* <Groups/>
*/
import styled from 'styled-components';
// import { Link, Switch, Route } from 'react-router-dom';

function Groups(){
  return (
    <Main>
      <h1>Groups Component Created Successfully</h1>
    </Main>
  );
}

/*
Groups.propTypes = {
  //  [variable-name]: PropTypes.[type],
};
*/

export default Groups;

const Main = styled.div`
background-color: black;
font-family: sans-serif;
padding-top: 50px;
color: white;
`;
