// Autogenerated using npm run gen Group
/*
* Copy to other files
* import Group from './Group';
* <Group/>
*/
import styled from 'styled-components';

function Group(props){

  function handleDisplayGroupSelected()
  {
    console.log(props.groupName+'was selected with Id: '+props.id);
  }


  return (
    <Main>
      <Name onClick={handleDisplayGroupSelected}>{props.groupName}</Name>
      <p>Id: {props.id}</p>
    </Main>
  );
}

Group.propTypes = {
  groupName: PropTypes.string,
  id: PropTypes.string,
};

export default Group;

const Main = styled.div`

`;

const Name = styled.h4`
background-color: grey;
&:hover ${Name} {
  background-color: blue;
}
`;
