// Autogenerated using npm run gen Group
/*
* Copy to other files
* import Group from './Group';
* <Group/>
*/
import styled from 'styled-components';
// import PropTypes from 'prop-types';
// import { Link, Switch, Route } from 'react-router-dom';

function Group(props){
  return (
    <Main>
      <h5>{props.group}</h5>
    </Main>
  );
}

/*
Group.propTypes = {
  //  [variable-name]: PropTypes.[type],
};
*/

export default Group;

const Main = styled.div`

`;
