// Autogenerated using npm run gen Groups
/*
* Copy to other files
* import Groups from './Groups';
* <Groups/>
*/
import styled from 'styled-components';
import ChatList from './ChatList';
// import { Link, Switch, Route } from 'react-router-dom';

//Right side should contain current joing group Discussions
// Details Groups name and a Public/Private descriptor

function Groups(){
  return (
    <Main>
      <h1>Groups</h1>
      <div className="row">
        <div className="col-md-3"><ChatList/></div>
      </div>
    </Main>
  );
}

/*
Groups.propTypes = {
  //  [variable-name]: PropTypes.[type],
};
*/

export default Groups;

const Main = styled.div`
background-color: black;
font-family: sans-serif;
padding-top: 50px;
color: white;
`;
