// Autogenerated using npm run gen Login
/*
* Copy to other files
* import Login from './Login';
* <Login/>
*/
import styled from 'styled-components';
// import { Link, Switch, Route } from 'react-router-dom';

function Login(){
  return (
    <Main>
      <h1>User Login</h1>
    </Main>
  );
}

/*
Login.propTypes = {
  //  [variable-name]: PropTypes.[type],
};
*/

export default Login;

const Main = styled.div`
background-color: black;
font-family: sans-serif;
color: white;
`;
