// Autogenerated using npm run gen MessageForm
/*
* Copy to other files
* import MessageForm from './MessageForm';
* <MessageForm/>
*/
import styled from 'styled-components';
// import { v4 } from 'uuid';

function MessageForm(){

  let _message;
  _message = null;
  function handleNewMessageFormSubmission(event)
  {
    event.preventDefault();
    // props.onNewMessageCreation({message: _message.value, , id: v4()});
    console.log(_message.value);
    _message.value = '';
  }

  return (
    <Main>
      <form className="row" onSubmit={handleNewMessageFormSubmission}>
        <textarea placeholder='New Message'
          className="col-md-9"
          id='issue'
          ref={(textarea) => {_message = textarea;}}/>
        <div className='col-md-3'>
          <button className='btn btn-submit' type="submit">Submit</button>
        </div>
      </form>
    </Main>
  );
}

/*
MessageForm.propTypes = {
  //  [variable-name]: PropTypes.[type],
};
*/

export default MessageForm;

const Main = styled.div`

`;
