// Autogenerated using npm run gen Message
/*
* Copy to other files
* import Message from './Message';
* <Message/>
*/
import styled from 'styled-components';

function Message(props){
  return (
    <Main>
      <p>{props.message}</p>
    </Main>
  );
}

Message.propTypes = {
  message: PropTypes.string,
};

export default Message;

const Main = styled.div`

`;
