// Autogenerated using npm run gen MessageForm
/*
* Copy to other files
* import MessageForm from './MessageForm';
* <MessageForm/>
*/
import styled from 'styled-components';
// import PropTypes from 'prop-types';
// import { Link, Switch, Route } from 'react-router-dom';

function MessageForm(){
  return (
    <Main>
      <div className='row'>
        <div classname='col-md-9'>
          <textarea placeholder='Message Box' cols='100'></textarea>
        </div>
        <div classname='col-md-3'>
          <button className='btn btn-submit'>Submit</button>
        </div>
      </div>
    </Main>
  );
}

/*
MessageForm.propTypes = {
  //  [variable-name]: PropTypes.[type],
};
*/

export default MessageForm;

const Main = styled.div`

`;
