// Autogenerated using npm run gen Message
/*
* Copy to other files
* import Message from './Message';
* <Message/>
*/
import styled from 'styled-components';
// import PropTypes from 'prop-types';
// import { Link, Switch, Route } from 'react-router-dom';

function Message(){
  return (
    <Main>
      <h1>Message Component Created Successfully</h1>
    </Main>
  );
}

/*
Message.propTypes = {
  //  [variable-name]: PropTypes.[type],
};
*/

export default Message;

const Main = styled.div`
background-color: black;
font-family: sans-serif;
padding-top: 50px;
color: white;
`;


